"""
Database configuration for Aviation Weather System
Auto-generated by setup_postgis.sh
"""

DATABASE_CONFIG = {
    'dbname': 'avwx_data',
    'user': 'avwx_user',
    'password': 'change_me_in_production',
    'host': '192.168.0.60',
    'port': 5432
}

# Connection string for SQLAlchemy
SQLALCHEMY_DATABASE_URI = f"postgresql://{DATABASE_CONFIG['user']}:{DATABASE_CONFIG['password']}@{DATABASE_CONFIG['host']}:{DATABASE_CONFIG['port']}/{DATABASE_CONFIG['dbname']}"

# Connection string for psycopg2
def get_connection():
    """Get psycopg2 database connection"""
    import psycopg2
    return psycopg2.connect(**DATABASE_CONFIG)
