###
###	NEXRAD2 
###
##	FILE	/home/ldm/var/data/NEXRAD2/\2/\1/tmp/\1_\2_\3

### L2-BZIP2/KILN/20211029191353/511/9/I/V06/0

### NEW NEXRAD2 processing... We'll move it to its rightful place after testing
###
###     L2-BZIP2/(KSRX)/(20210407)(20145)7/(123)/(25)/(I)/V06/0
#NEXRAD2		^L2-BZIP2/(....)/([0-9][0-9][0-9][0-9][0-1][0-9][0-3][0-9])([0-2][0-9][0-5][0-9][0-9][0-9])/([0-9]*)/[0-9]*/(S|I|E)
#	PIPE	-metadata	/home/ldm/ldm-alchemy/l2assemble.py -v -t 960 -d /LDM/NEXRAD2 -f raw --threads 10 -p "{0.site}" -n "{0.site}_{0.dt:%%Y%%m%%d_%%H%%M%%S}" -f gz

#NEXRAD		^L2-BZIP2/(....)/([0-9][0-9][0-9][0-9][0-1][0-9][0-3][0-9])([0-2][0-9][0-5][0-9][0-9][0-9])/([0-9]*)/[0-9]*/(S|I|E)
#	PIPE	-metadata	/home/ldm/scripts/l2assemble.py -v -t 960 -d /LDM/CAP/nwx/radar -f raw --threads 10 -p "{0.site}" -n "{0.site}_{0.dt:%%Y%%m%%d_%%H%%M%%S}"
###
### File Model Data Message packets separately, since they are on a different
### time schedule

#### 23 APR 2019 gc
NEXRAD2		^L2-BZIP2/(....)/([0-9][0-9][0-9][0-9][0-1][0-9][0-3][0-9])([0-2][0-9][0-5][0-9][0-9][0-9])/[0-9]*/([0-9]*)/M
	FILE	-close	/LDM/NEXRAD2/level2_model/\1/Level2MDM_\1_\2_\3.ar2v
####

### 11 JUL 23 gc -- Karen Cooper's version
# L2-BZIP2/KGRB/20230712033316/261/19/I/V06/0
NEXRAD2	^L2-(BZIP2)/(....)/([0-9][0-9][0-9][0-9][0-1][0-9][0-3][0-9][0-2][0-9][0-5][0-9][0-9][0-9])(.*)/(S|I|E)/
	FILE		/LDM/NEXRAD2/Level2/\2-\3.L2

### 27 JUN 21 gc
#NEXRAD3		^rad/NEXRCOMP/1km/n0r_(........)_(....)
#	FILE	-close	/LDM/NEXRAD3/images/NEXRCOMP/1km/n0r/n01_\1\2

NEXRAD	    SDUS.. (....) ([0-3][0-9])([0-2][0-9])([0-6][0-9]).*/p(...)(...)
	FILE	-overwrite	-close	/LDM/NEXRAD3/NIDS//\4_(\1:yyyy)(\1:mm)\1_\2\3


