# Configuration file for "scour" utility, to delete all files older than a
# specified number of days from specified directories and all their
# subdirectories.  Scour should be invoked periodically by cron(8).
#
# Each line consists of a directory, a retention time (in days), and
# (optionally) a shell filename pattern for files to be deleted.  If no
# filename pattern is specified, "*" representing all files not beginning with
# "." is assumed.  The syntax "~user" is understood.  Non-absolute pathnames
# are relative to the directory `regutil /pqact/datadir-path`.
#
# A hash in column one indicates a comment line.

# Directory			Days-old	Optional-filename-pattern

#dir1		            2
#dir2			        2		*.foo
/LDM			2		
/LDM/text/metar		1
/LDM/radar/level3	1
/LDM/radar/level2	1
/LDM/text/taf		1
/var/www/cap_winds_app/model_data	1
#/var/www/cap_winds_app/model_data	2	gfs.202*
/LDM/fire		1
/LDM/satellite 		1
/LDM/hds/tpw		1
/home/ldm/var/logs	3
/LDM/WWA		1	
/LDM/models		1

